from wtforms import Form, SelectMultipleField, SubmitField, StringField, BooleanField
from wtforms.validators import DataRequired

class organizationFilterForm(Form):
	age_choices = [
		('PreK (Age 0-3)', 'PreK (Age 0-3)'),
		('PreK (Age 3-5)', 'PreK (Age 3-5)'),
		('Grades K-8', 'Grades K-8'),
		('Grades 9-12', 'Grades 9-12'),
		('Adult', 'Adult'),
	]

	type_choices = [
		('Pre-Reading', 'Pre-Reading'),
		('Pre-Writing', 'Pre-Writing'),
		('Writing', 'Writing'),
		('Reading', 'Reading'),
		('Expository Writing', 'Expository Writing'),
		('Create Writing', 'Creative Writing'),
		('Dramatic Play', 'Dramatic Play'),
		('Book Access & Distribution', 'Book Access & Distribution'),
		('ELL/ESL', 'ELL/ESL'),
		('GED Prep', 'GED Prep'),
		('Workforce Development', 'Workforce Development'),
		('Teacher Training', 'Teacher Training'),
		('Cirriculum Development', 'Cirriculum Development'),
		('Other', 'Other'),
	]

	neighborhoods = [
		('Far North Side', 'Rogers Park'),
		('Far North Side', 'West Ridge'),
		('Far North Side', 'Edgewater'),
		('Far North Side', 'Andersonville'),
		('Far North Side', 'Uptown'),
		('Far North Side', 'Lincoln Sqaure'),
		('Far North Side', "O'Hare"),
		('Far North Side', 'Jefferson Park'),
		('Far North Side', 'Sauganash,Forest Glen'),
		('Far North Side', 'North Park'),
		('Far North Side', 'Norwood Park'),
		('Far North Side', 'Edison Park'),

		('Northwest Side', 'Hermosa'),
		('Northwest Side', 'Portage Park'),
		('Northwest Side', 'Irving Park'),
		('Northwest Side', 'Dunning'),
		('Northwest Side', 'Montclare'),
		('Northwest Side', 'Belmont Cragin'),

		('North Side', 'Sheffield & DePaul'),
		('North Side', 'Avondale'),
		('North Side', 'Logan Square'),
		('North Side', 'Lake View'),
		('North Side', 'Lincoln Park'),
		('North Side', 'Bucktown'),
		('North Side', "Wrigleyville"),
		('North Side', 'Boystown'),

		('West Side', 'United Center'),
		('West Side', 'Humboldt Park'),
		('West Side', 'North Lawndale'),
		('West Side', 'Little Village'),
		('West Side', 'Greektown'),
		('West Side', 'West Loop'),
		('West Side', "Little Italy, UIC"),
		('West Side', 'Pilsen'),
		('West Side', 'East Village'),
		('West Side', 'West Town'),
		('West Side', 'Wicker Park'),
		('West Side', 'Ukrainian Village'),
		('West Side', 'Galewood'),
		('West Side', 'Austin'),
	
		('Central', 'Printers Row'),
		('Central', 'Loop'),
		('Central', 'Museum Campus'),
		('Central', 'Magnificent Mile'),
		('Central', 'Grant Park'),
		('Central', 'Rush & Division'),
		('Central', 'Streeterville'),
		('Central', 'Millenium Park'),
		('Central', 'Near South Side'),
		('Central', 'Old Town'),
		('Central', 'Gold Coast'),
		('Central', 'RIver North'),

		('South Side', 'Grand Boulevard'),
		('South Side', 'Armour Square'),
		('South Side', 'Grand Crossing'),
		('South Side', 'Jackson Park'),
		('South Side', 'Bronzeville'),
		('South Side', 'Oakland'),
		('South Side', 'Fuller Park'),
		('South Side', 'Woodlawn'),
		('South Side', 'Kenwood'),
		('South Side', 'South Shore'),
		('South Side', 'Washington Park'),
		('South Side', 'Chinatown'),
		('South Side', 'Hyde Park'),
		('South Side', 'Bridgeport'),

		('Southwest Side', 'Garfield Ridge'),
		('Southwest Side', 'New City'),
		('Southwest Side', 'Englewood'),
		('Southwest Side', 'Chicago Lawn'),
		('Southwest Side', 'Archer Heights'),
		('Southwest Side', 'Brighton Park'),
		('Southwest Side', 'Mckinley Park'),
		('Southwest Side', 'West Elsdon'),
		('Southwest Side', 'Gage Park'),
		('Southwest Side', 'Clearing'),
		('Southwest Side', 'West Lawn'),

		('Far Southeast', 'Avalon Park'),
		('Far Southeast', 'Burnside'),
		('Far Southeast', 'Calumet Heights'),
		('Far Southeast', 'East Side'),
		('Far Southeast', 'West Pullman'),
		('Far Southeast', 'Pullman'),
		('Far Southeast', "Riverdale"),
		('Far Southeast', 'Hegewisch'),
		('Far Southeast', 'Chatham'),
		('Far Southeast', 'South Chicago'),
		('Far Southeast', 'Roseland'),
		('Far Southeast', 'South Deering'),

		('Far Southwest', 'Ashburn'),
		('Far Southwest', 'Mount Greenwood'),
		('Far Southwest', 'Morgan Park'),
		('Far Southwest', 'Auburn Gresham'),
		('Far Southwest', 'Beverly'),
		('Far Southwest', 'Washington Heights'),

		('South Side', 'Bridgeport'),
		('South Side', 'Chinatown'),
		('North Side', 'Lakeview'),
		('West Side', 'United Center'),
		('South Side', 'Armour Square'),
		('Far Southwest Side', 'Avalon Park'),
	]

	zipcodes = [
		('60601', '60601'),
		('60602', '60602'),
		('60603', '60603'),
		('60604', '60604'),
		('60606', '60606'),
		('60607', '60607'),
		('60608', '60608'),
		('60609', '60609'),
		('60610', '60610'),
		('60611', '60611'),
		('60612', '60612'),
		('60613', '60613'),
		('60614', '60614'),
		('60615', '60615'),
		('60616', '60616'),
		('60617', '60617'),
		('60618', '60618'),
		('60619', '60619'),
		('60620', '60620'),
		('60621', '60621'),
		('60622', '60622'),
		('60623', '60623'),
		('60624', '60624'),
		('60625', '60625'),
		('60626', '60626'),
		('60627', '60627'),
		('60628', '60628'),
		('60629', '60629'),
		('60630', '60630'),
		('60631', '60631'),
		('60632', '60632'),
		('60633', '60633'),
		('60634', '60634'),
		('60635', '60635'),
		('60636', '60636'),
		('60637', '60637'),
		('60638', '60638'),
		('60639', '60639'),
		('60640', '60640'),
		('60641', '60641'),
		('60642', '60642'),
		('60643', '60643'),
		('60644', '60644'),
		('60645', '60645'),
		('60646', '60646'),
		('60647', '60647'),
		('60648', '60648'),
		('60649', '60649'),
		('60651', '60651'),
		('60652', '60652'),
		('60653', '60653'),
		('60654', '60654'),
		('60655', '60655'),
		('60656', '60656'),
		('60657', '60657'),
		('60659', '60659'),
		('60660', '60660'),
		('60661', '60661'),
		('60666', '60666'),
		('60707', '60707'),
		('60827', '60827'),
		('60940', '60940'),
	]

	neighborhoods = SelectMultipleField('Filter by neighborhoods:', choices=neighborhoods)
	select_age = SelectMultipleField('Filter by program age group:', choices=age_choices)
	select_type = SelectMultipleField('Filter by program type:', choices=type_choices)
	search_name = StringField('Filter by name:', validators=[DataRequired()])
	zipcodes = SelectMultipleField('Filter by zipcodes:', choices=zipcodes)
	submit1 = SubmitField('Filter')

class sendTextForm(Form):
	user_number = StringField('Your phone number', validators=[DataRequired()])
	user_email = StringField('Your email address', validators=[DataRequired()])
	program_information = StringField('program_information', validators=[DataRequired()])
	submit2 = SubmitField('Send!')