"""empty message

Revision ID: 694d35f9047b
Revises: 817c3d3378d3
Create Date: 2019-10-15 22:38:38.678407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '694d35f9047b'
down_revision = '817c3d3378d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neighborhood_programs', sa.Column('region_id', sa.Integer(), nullable=False))
    op.drop_constraint('neighborhood_programs_ibfk_2', 'neighborhood_programs', type_='foreignkey')
    op.create_foreign_key(None, 'neighborhood_programs', 'regions', ['region_id'], ['id'])
    op.drop_column('neighborhood_programs', 'neighborhood_id')
    op.create_foreign_key(None, 'neighborhoods', 'regions', ['region_id'], ['id'])
    op.alter_column('regions', 'name',
               existing_type=mysql.CHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regions', 'name',
               existing_type=mysql.CHAR(length=80),
               nullable=True)
    op.drop_constraint(None, 'neighborhoods', type_='foreignkey')
    op.add_column('neighborhood_programs', sa.Column('neighborhood_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'neighborhood_programs', type_='foreignkey')
    op.create_foreign_key('neighborhood_programs_ibfk_2', 'neighborhood_programs', 'neighborhoods', ['neighborhood_id'], ['id'])
    op.drop_column('neighborhood_programs', 'region_id')
    # ### end Alembic commands ###
