"""empty message

Revision ID: 780022324841
Revises: 694d35f9047b
Create Date: 2019-11-18 17:02:33.444445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '780022324841'
down_revision = '694d35f9047b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('organizations', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'organizations', ['longitude'])
    op.create_unique_constraint(None, 'organizations', ['latitude'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'longitude')
    op.drop_column('organizations', 'latitude')
    op.alter_column('neighborhoods', 'SHAPE',
               existing_type=sa.NullType(),
               nullable=True)
    # ### end Alembic commands ###
