"""empty message

Revision ID: 817c3d3378d3
Revises: d530a9a94301
Create Date: 2019-10-08 19:09:34.232182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817c3d3378d3'
down_revision = 'd530a9a94301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('schools', sa.Column('grade', sa.String(length=80), nullable=False))
    op.add_column('schools', sa.Column('type', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'type')
    op.drop_column('schools', 'grade')
    op.drop_column('schools', 'address')
    # ### end Alembic commands ###
