"""empty message

Revision ID: d530a9a94301
Revises: f5de16b1957a
Create Date: 2019-10-03 23:20:22.476701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd530a9a94301'
down_revision = 'f5de16b1957a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('state', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'state')
    # ### end Alembic commands ###
