"""empty message

Revision ID: e4c9be863f6b
Revises: 
Create Date: 2019-09-28 19:18:30.208072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4c9be863f6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'program_types', 'program_type', ['program_type_id'], ['id'])
    op.create_foreign_key(None, 'program_types', 'programs', ['program_iid'], ['id'])
    op.drop_column('program_types', 'type_id')
    op.drop_column('program_types', 'id')
    op.drop_column('program_types', 'program_id')
    op.add_column('programs', sa.Column('open_public_school_enrollement', sa.Boolean(), nullable=False))
    op.alter_column('programs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('programs', 'volunteers_needed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_unique_constraint(None, 'programs', ['org_id'])
    op.create_unique_constraint(None, 'programs', ['name'])
    op.drop_column('programs', 'open_to_public_school_enrollment')
    op.drop_column('school_zips', 'id')
    op.alter_column('schools', 'name',
               existing_type=mysql.CHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'schools', ['name'])
    op.drop_column('schools', 'lat')
    op.drop_column('schools', 'log')
    op.alter_column('zip_codes', 'name',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_unique_constraint(None, 'zip_codes', ['name'])
    op.create_foreign_key(None, 'zipcode_programs', 'zip_codes', ['zip_id'], ['id'])
    op.drop_column('zipcode_programs', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zipcode_programs', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'zipcode_programs', type_='foreignkey')
    op.drop_constraint(None, 'zip_codes', type_='unique')
    op.alter_column('zip_codes', 'name',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('schools', sa.Column('log', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('lat', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schools', type_='unique')
    op.alter_column('schools', 'name',
               existing_type=mysql.CHAR(length=100),
               nullable=True)
    op.add_column('school_zips', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('programs', sa.Column('open_to_public_school_enrollment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'programs', type_='unique')
    op.drop_constraint(None, 'programs', type_='unique')
    op.alter_column('programs', 'volunteers_needed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('programs', 'org_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('programs', 'open_public_school_enrollement')
    op.add_column('program_types', sa.Column('program_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('program_types', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('program_types', sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'program_types', type_='foreignkey')
    op.drop_constraint(None, 'program_types', type_='foreignkey')
    # ### end Alembic commands ###
