"""empty message

Revision ID: f5de16b1957a
Revises: e4c9be863f6b
Create Date: 2019-10-03 23:09:12.955682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5de16b1957a'
down_revision = 'e4c9be863f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('organizations', sa.Column('zipcode', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'zipcode')
    op.drop_column('organizations', 'city')
    # ### end Alembic commands ###
